project_id = "lgvhgmiuyxbwfbcbzhdh"

[functions.admin-login]
verify_jwt = false

[functions.admin-validate-session]
verify_jwt = false

[functions.admin-logout]
verify_jwt = false

[functions.admin-get-students]
verify_jwt = false

[functions.admin-update-student]
verify_jwt = false

[functions.admin-delete-student]
verify_jwt = false

[functions.admin-bulk-delete-students]
verify_jwt = false

[functions.student-login]
verify_jwt = false

[functions.student-get-data]
verify_jwt = false

[functions.student-update-data]
verify_jwt = false

[functions.student-register]
verify_jwt = false
